export const LOGIN_DATA = 'LOGIN_DATA';
export const MY_INFO = 'MY_INFO';
export const MANAGER_INFO = 'MANAGER_INFO';
export const CLIENT_LIST = 'CLIENT_LIST';
export const CLIENT_DETAIL = 'CLIENT_DETAIL';
export const GET_PAYMENT_LIST = 'GET_PAYMENT_LIST';
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const DASHBOARD_LIST = 'DASHBOARD_LIST';
export const DASHBOARD_MESSAGE_LIST = 'DASHBOARD_MESSAGE_LIST';
export const REQUEST_INFO = 'REQUEST_INFO'
export const REQUEST_INFO_BY_ID = 'REQUEST_INFO_BY_ID'
export const FOLDER_LIST = 'FOLDER_LIST'
export const DOCUMENT_INFO_FOLDER = 'DOCUMENT_INFO_FOLDER'
export const FILE_INFO = 'FILE_INFO'
export const OFFICE_INFO = 'OFFICE_INFO'
export const PARTNER_INFO = 'PARTNER_INFO'
export const MY_OFFICE_INFO = 'MY_OFFICE_INFO'
export const FILE_UPLOAD_TOKEN = 'FILE_UPLOAD_TOKEN'
export const EDITOR_TEXT = "EDITOR_TEXT"
export const GET_LIB_FILES = "GET_LIB_FILES"
export const DASHBOARD_LIST_TWO = "DASHBOARD_LIST_TWO"
export const INTEREST_LIST = "INTEREST_LIST"
export const PROFESSION_LIST = "PROFESSION_LIST"
export const ADD_CLIENT_SETUP = "ADD_CLIENT_SETUP"





