# Resolve react_native_pods.rb with node to allow for hoisting
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported

target 'TaxTree' do
  config = use_native_modules!
 
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'
  #pod 'React-Core', :path => '../node_modules/react-native/React'
  #pod 'React-Core', :path => '../node_modules/react-native/React-Core'

  #pod 'RCT-Folly', :git => 'https://github.com/facebook/folly.git'
 
  #permissions_path = '../node_modules/react-native-permissions/ios'
 # pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
 # pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
 # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
 
  target 'TaxTreeTests' do
    inherit! :complete
    # Pods for testing
  end

  #use_flipper!({ 'Flipper' => '0.87.0' }) # Replace with the Flipper version you need

  post_install do |installer|
    react_native_post_install(installer)
  end
end
